### PR TITLE
Removed support for MRI ruby versions lower than 2.2

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
ditto

### CODE REVIEW

**Comment by jodosha** [comment]
@AlfonsoUceda This looks good :+1: But we should hold on until the release and keep merging master here.

**Comment by teddy-ma** [comment]
Should [this description](https://github.com/lotus/utils/blob/master/lib/lotus/utils/attributes.rb#L10~#L11) to be removed since ruby 2.2 has Symbol GC?

**Comment by AlfonsoUceda** [comment]
@teddy-ma supporting mri ruby2.2+ that class will dissapear

**Comment by jodosha** [comment]
@teddy-ma @AlfonsoUceda Yeah, that class will no longer be used. But we won't merge those 2.2 only PRs for a while.

**Pull request closed without merging**
