### PR TITLE
Fix String#classify for dash separators

### PR DESCRIPTION
**Pull request by davydovanton**
Now `classify` method returns `'Test::App'` for `'test-app'` string. 

Reference link:
  https://github.com/lotus/lotus/pull/449#discussion_r49570468

### CODE REVIEW

**Comment by joneslee85** [comment]
:+1:

**Comment by AlfonsoUceda** [comment]
@joneslee85 @davydovanton take care of this comment https://github.com/lotus/lotus/pull/449#issuecomment-171240677

This shouldn't be merged for now, @davydovanton what do you think to run test in every gem with this lotus utils branch?

**Comment by jodosha** [comment]
@AlfonsoUceda This is a fix for a `#classify` bug that should be addressed regardless of lotus/lotus#449.
I'm merging this, but that means we need to make sure that `"app-name" => "AppName"` is respected in `lotusrb`.

See https://github.com/lotus/lotus/pull/449#issuecomment-171575901

**Comment by jodosha** [comment]
@davydovanton Thank you. Merging this. :+1:

**Comment by AlfonsoUceda** [comment]
@jodosha understand it! ;)

**Comment by davydovanton** [comment]
thanks for merge, @jodosha :smiley:

**Pull request merged**
